pygmentsStyle = "solarized-light"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = false

baseURL = "https://jefclaes.be/"
languageCode = "en-us"
title = "Jef Claes"
theme = "ink"


googleAnalytics = "UA-6239073-1"


[permalinks]
post = "/:year/:month/:title"

[params]
	subtitle = "On software and life"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
	
	featherIconsCDN = true
	# customCSS  = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

[mediaTypes]
  [mediaTypes."application/rss"]
    suffixes = []

[outputs]
home = [ "RSS", "HTML"]
 
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feeds/posts/default"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jefclaes"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jefclaes"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jefclaes"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://feed.jefclaes.be"

[taxonomies]
tag = "tags"