baseURL = "https://jefclaes.be/"
title = "Jef Claes"
theme = "PaperMod"
paginate = 10
locale = "en-us"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
  style = "monokai"
  noClasses = true

[params]
  env = "production"
  author = "Jef Claes"
  description = "On software and life"

  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

[params.homeInfoParams]
  Title = "Jef Claes"
  Content = "On software and life"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/jefclaes"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/jefclaes"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/jefclaes"

[[params.socialIcons]]
  name = "rss"
  url = "/feeds/posts/default"

[mediaTypes]
  [mediaTypes."application/rss"]
    suffixes = []

[outputs]
home = ["RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feeds/posts/default"

[taxonomies]
tag = "tags"

[permalinks]
post = "/:year/:month/:title"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
